version: 2.1

jobs:
  checkout:
    docker:
      - image: circleci/node:12.13.0-browsers
    environment:
      TERM: xterm
    working_directory: ~/app
    steps:
      - checkout

  prepare:
    docker:
      - image: circleci/node:12.13.0-browsers
    environment:
      TERM: xterm
    working_directory: ~/app
    steps:
      - restore_cache:
          keys:
            - v1-deps-{{ .Branch }}-{{ checksum "package.json" }}
            - v1-deps-{{ .Branch }}
            - v1-deps
      - run:
          name: Install dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          key: v1-deps-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - node_modules
            - ~/.cache
      - persist_to_workspace:
          root: .
          paths:
            - node_modules

  lint:
    docker:
      - image: circleci/node:12.13.0-browsers
    environment:
      TERM: xterm
    working_directory: ~/app
    steps:
      - restore_cache:
          keys:
            - v1-deps-{{ .Branch }}-{{ checksum "package.json" }}
            - v1-deps-{{ .Branch }}
            - v1-deps
      - run:
          name: Run linters
          command: yarn lint

  test-unit:
    docker:
      - image: circleci/node:12.13.0-browsers
      - image: circleci/postgres:10.4-alpine
    environment:
      TERM: xterm
    working_directory: ~/app
    steps:
      - restore_cache:
          keys:
            - v1-deps-{{ .Branch }}-{{ checksum "package.json" }}
            - v1-deps-{{ .Branch }}
            - v1-deps
      - run:
          name: Run tests
          command: yarn test:ci
      - store_test_results:
          path: .tmp/test-results

workflows:
  version: 2
  build:
    jobs:
      - checkout
      - build:
          requires:
            - checkout
      - lint:
          requires:
            - build
      - test-unit:
          requires:
            - lint
