version: 2.1

jobs:
  pre-build:
    docker:
      - image: circleci/node:12.13.0
    environment:
      TERM: xterm
    working_directory: ~/app
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-deps-{{ .Branch }}-{{ checksum "package.json" }}
            - v1-deps-{{ .Branch }}
            - v1-deps
      - run:
          name: Installing dependencies
          command: yarn install --frozen-lockfile
      - run:
          name: Build common
          command: yarn run build:common
      - run:
          name: Build ui-common
          command: yarn run build:ui-common
      - run:
          name: Running linters
          command: yarn lint
      - run:
          name: Running unit tests
          command: yarn test:ci
      - save_cache:
          key: v1-deps-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - node_modules
            - ~/.cache
      - store_test_results:
          path: .tmp/test-results

  build:
    docker:
      - image: circleci/node:12.13.0
    environment:
      TERM: xterm
    working_directory: ~/app
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-deps-{{ .Branch }}-{{ checksum "package.json" }}
            - v1-deps-{{ .Branch }}
            - v1-deps
      - run:
          name: Transpiling common
          command: yarn -s build:common
      - run:
          name: Transpiling ui-common
          command: yarn -s build:ui-common
      - run:
          name: Transpiling service
          command: yarn -s build:service
      - run:
          name: Transpiling ui
          command: yarn -s build:ui

workflows:
  version: 2
  features:
    jobs:
      - pre-build
      - build:
          requires:
            - pre-build
          filters:
            branches:
              only:
                - master
