version: 2.1

jobs:
  test:
    docker:
      - image: circleci/node:14.2.0
    environment:
      TERM: xterm
    working_directory: ~/app
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-deps
            - v1-deps-{{ .Branch }}
            - v1-deps-{{ .Branch }}-{{ checksum "package.json" }}
      - run:
          name: Installing dependencies
          command: yarn install --frozen-lockfile
      - run:
          name: Running linters
          command: yarn lint
      - run:
          name: Build common dependencies
          command: yarn -s build:common
      - run:
          name: Running unit tests
          command: yarn test:ci
      - save_cache:
          key: v1-deps-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - node_modules
            - ~/.cache
      - store_test_results:
          path: .tmp/test-results

  build-service:
    docker:
      - image: circleci/node:14.2.0
    environment:
      TERM: xterm
    working_directory: ~/app
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-deps
            - v1-deps-{{ .Branch }}
            - v1-deps-{{ .Branch }}-{{ checksum "package.json" }}
      - run:
          name: Check the service needs built
          command: ./.circleci/exit-untouched.sh packages/common packages/service
      - run:
          name: Build service
          command: yarn -s build:service

  build-ui:
    docker:
      - image: circleci/node:14.2.0
    environment:
      TERM: xterm
    working_directory: ~/app
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-deps
            - v1-deps-{{ .Branch }}
            - v1-deps-{{ .Branch }}-{{ checksum "package.json" }}
      - run:
          name: Check the ui needs built
          command: ./.circleci/exit-untouched.sh packages/common packages/ui-common packages/ui
      - run:
          name: Build all the things
          command: yarn -s build:ui

  deploy-service:
    docker:
      - image: circleci/node:14.2.0
    steps:
      - checkout
      - run:
          name: Check the service needs pushed
          command: ./.circleci/exit-untouched.sh packages/common packages/service
      - run:
          name: Deploy service to Heroku
          command: |
            git push --force https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME_SERVICE.git master

  deploy-ui:
    docker:
      - image: circleci/node:14.2.0
    steps:
      - checkout
      - run:
          name: Check the ui needs built
          command: ./.circleci/exit-untouched.sh packages/common packages/ui-common packages/ui
      - run:
          name: Deploy ui to Heroku
          command: |
            git push --force https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME_UI.git master

workflows:
  version: 2
  features:
    jobs:
      - test
      - build-service:
          requires:
            - test
          filters:
            branches:
              only:
                - master
      - build-ui:
          requires:
            - test
          filters:
            branches:
              only:
                - master
      # - approve-deployment-service:
      #     type: approval
      #     requires:
      #       - build-service
      # - approve-deployment-ui:
      #     type: approval
      #     requires:
      #       - build-ui
      - deploy-service:
          requires:
            - build-service
          filters:
            branches:
              only:
                - master
      - deploy-ui:
          requires:
            - build-ui
          filters:
            branches:
              only:
                - master
