version: '3.7'

services:
  db:
    container_name: db
    image: postgres:10.4-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=boilerplate-monorepo
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    volumes:
      - ./.tmp/db/data:/var/lib/postgresql/data
    restart: unless-stopped

  ui:
    container_name: ui
    build:
      context: .
      dockerfile: ./docker/Dockerfile.ui
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - yarn-cache-ui:/yarn

  service:
    container_name: service
    build:
      context: .
      dockerfile: ./docker/Dockerfile.service
    ports:
      - 4000:4000
    environment:
      - TYPEORM_HOST=db
    depends_on:
      - db
    volumes:
      - .:/app
      - yarn-cache-service:/yarn

volumes:
  yarn-cache-ui:
  yarn-cache-service:
