version: '3.7'

services:
  db:
    container_name: db
    image: postgres:10.4-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=boilerplate-monorepo
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    volumes:
      - ./.tmp/db/data:/var/lib/postgresql/data
    restart: unless-stopped

  cache:
    command: ['redis-server', '--appendonly', 'yes']
    container_name: cache
    image: redis:5.0.7-alpine
    ports:
      - 6379:6379
    volumes:
      - ./.tmp/cache/data:/data

  cache-ui:
    container_name: cache-ui
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=local:cache:6379
    ports:
      - 8081:8081

  email:
    container_name: email
    image: mailhog/mailhog
    restart: always
    environment:
      MH_MAILDIR_PATH: /tmp
      MH_STORAGE: maildir
    ports:
      - 1025:1025
      - 8025:8025
    volumes:
      - email-dir:/tmp

  ui:
    container_name: ui
    build:
      context: .
      dockerfile: ./docker/Dockerfile.ui
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - yarn-cache-ui:/yarn

  service:
    container_name: service
    build:
      context: .
      dockerfile: ./docker/Dockerfile.service
    ports:
      - 4000:4000
    depends_on:
      - cache
      - db
    volumes:
      - .:/app
      - yarn-cache-service:/yarn

volumes:
  email-dir:
  yarn-cache-ui:
  yarn-cache-service:
