version: '3.7'

services:
  db:
    container_name: db
    image: postgres:alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=boilerplate-monorepo
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    volumes:
      - ./.tmp/db/data:/var/lib/postgresql/data
    restart: unless-stopped

  ui:
    container_name: ui
    build:
      context: .
      dockerfile: ./docker/Dockerfile.ui
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - node_modules-cache:/app/node_modules
      - node_modules-cache-common:/app/packages/common/node_modules
      - node_modules-cache-ui:/app/packages/ui/node_modules
      - node_modules-cache-ui-common:/app/packages/ui-common/node_modules
      - yarn-cache:/yarn

volumes:
  node_modules-cache:
  node_modules-cache-common:
  node_modules-cache-ui:
  node_modules-cache-ui-common:
  yarn-cache:
