version: '3.7'

services:
  db:
    container_name: db
    image: postgres:12.2-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=boilerplate-monorepo
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    volumes:
      - data-db:/var/lib/postgresql/data
    restart: unless-stopped

  cache:
    command: ['redis-server', '--appendonly', 'yes']
    container_name: cache
    image: redis:5.0.7-alpine
    ports:
      - 6379:6379
    volumes:
      - data-cache:/data

  cache-ui:
    container_name: cache-ui
    image: rediscommander/redis-commander
    restart: always
    environment:
      - REDIS_HOSTS=local:cache:6379
    ports:
      - 8081:8081

  email:
    container_name: email
    image: mailhog/mailhog
    restart: always
    environment:
      MH_MAILDIR_PATH: /tmp
      MH_STORAGE: maildir
    ports:
      - 1025:1025
      - 8025:8025
    volumes:
      - data-email:/tmp

volumes:
  data-cache:
  data-db:
  data-email:
  yarn-cache-service:
