overwrite: true
schema: 'http://localhost:4000/graphql'
documents: './src/shared/graphql/{mutation,query}/*.js'
generates:
  # ./.codegen/types.ts:
  #   plugins:
  #     - add: /* eslint-disable */
  #     - 'typescript'
  #     - 'typescript-operations'
  #     - 'typescript-react-apollo'
  #   config:
  #     withComponent: false
  #     withHOC: false
  #     withHooks: true
  ./.codegen/schema.json:
    plugins:
      - 'introspection'
