_type: export
__export_format: 4
__export_date: 2020-04-17T19:05:15.806Z
__export_source: insomnia.desktop.app:v7.1.1
resources:
  - _id: req_45c96e3cce6845569aaeb3db515b8cc3
    authentication: {}
    body:
      mimeType: application/graphql
      text: '{"query":"mutation UserLogin($input: UserLoginInput!)
        {\n  userLogin(input:
        $input)\n}\n","variables":{"input":{"username":"nclark","password":"Password!23"}}}'
    created: 1577800601451
    description: ""
    headers:
      - id: pair_da0e8e267c1940c0912468bcba4fcc12
        name: Content-Type
        value: application/json
    isPrivate: false
    metaSortKey: -1578263622751
    method: POST
    modified: 1586915550459
    name: UserLogin
    parameters: []
    parentId: fld_a2d0e0de6c984471bfb0d0cbef41a924
    settingDisableRenderRequestBody: false
    settingEncodeUrl: true
    settingFollowRedirects: global
    settingRebuildPath: true
    settingSendCookies: true
    settingStoreCookies: true
    url: "{{ graphqlUri  }}"
    _type: request
  - _id: fld_a2d0e0de6c984471bfb0d0cbef41a924
    created: 1577823938455
    description: ""
    environment: {}
    environmentPropertyOrder: null
    metaSortKey: -1577823938455
    modified: 1577823938455
    name: Mutations
    parentId: fld_9671057628d34a3bb9e7551fc59663c7
    _type: request_group
  - _id: fld_9671057628d34a3bb9e7551fc59663c7
    created: 1577801584588
    description: ""
    environment: {}
    environmentPropertyOrder: null
    metaSortKey: -1577801584588
    modified: 1577801584588
    name: User
    parentId: fld_4cbdf86a24044058bb7c82a348286bb7
    _type: request_group
  - _id: fld_4cbdf86a24044058bb7c82a348286bb7
    created: 1577800580776
    description: ""
    environment: {}
    environmentPropertyOrder: null
    metaSortKey: -1577800580876
    modified: 1578620103805
    name: GraphQL
    parentId: wrk_b673aad6c5df416ead4f262eb230cf9c
    _type: request_group
  - _id: wrk_b673aad6c5df416ead4f262eb230cf9c
    created: 1577800360578
    description: ""
    modified: 1577800755606
    name: "@boilerplate-monorepo"
    parentId: null
    _type: workspace
  - _id: req_cea84b50cb754a67bdc1c4cc0d72a250
    authentication:
      prefix: "{{ accessTokenPrefix  }}"
      token: "{{ accessToken }}"
      type: bearer
    body:
      mimeType: application/graphql
      text: '{"query":"mutation UserLogout
        {\n  userLogout\n}\n","operationName":"UserLogout"}'
    created: 1578962079443
    description: ""
    headers:
      - id: pair_da0e8e267c1940c0912468bcba4fcc12
        name: Content-Type
        value: application/json
    isPrivate: false
    metaSortKey: -1578263622738.5
    method: POST
    modified: 1586915536661
    name: UserLogout
    parameters: []
    parentId: fld_a2d0e0de6c984471bfb0d0cbef41a924
    settingDisableRenderRequestBody: false
    settingEncodeUrl: true
    settingFollowRedirects: global
    settingRebuildPath: true
    settingSendCookies: true
    settingStoreCookies: true
    url: "{{ graphqlUri  }}"
    _type: request
  - _id: req_24cc628cbee24f02adca311ed17f5c03
    authentication: {}
    body:
      mimeType: application/graphql
      text: '{"query":"mutation UserRegister($input:
        UserRegisterInput!){\n  userRegister(input:
        $input)\n}\n","variables":{"input":{"captchaToken":"CAPTCHA_TOKEN","givenName":"Nate","familyName":"Clark","email":"n8@n8io.com","passwordNew":"Password!23","username":"n8io"}},"operationName":"UserRegister"}'
    created: 1577801562443
    description: ""
    headers:
      - id: pair_da0e8e267c1940c0912468bcba4fcc12
        name: Content-Type
        value: application/json
    isPrivate: false
    metaSortKey: -1578263622726
    method: POST
    modified: 1587150298896
    name: UserRegister
    parameters: []
    parentId: fld_a2d0e0de6c984471bfb0d0cbef41a924
    settingDisableRenderRequestBody: false
    settingEncodeUrl: true
    settingFollowRedirects: global
    settingRebuildPath: true
    settingSendCookies: true
    settingStoreCookies: true
    url: "{{ graphqlUri  }}"
    _type: request
  - _id: req_28ec7023fa494ee99e76afb2abe71288
    authentication:
      prefix: "{{ accessTokenPrefix  }}"
      token: "{{accessToken}}"
      type: bearer
    body:
      mimeType: application/graphql
      text: '{"query":"mutation UserPasswordReset($input: UserPasswordResetInput!)
        {\n  userPasswordReset(input:
        $input)\n}\n","variables":{"input":{"id":"ck8za5m110000gpfk2kiq12yj","passwordNew":"Password!23","token":"k8za5wup0001gpfk0ly91hyl"}},"operationName":"UserPasswordReset"}'
    created: 1586830494842
    description: ""
    headers:
      - id: pair_da0e8e267c1940c0912468bcba4fcc12
        name: Content-Type
        value: application/json
    isPrivate: false
    metaSortKey: -1578263622725.2188
    method: POST
    modified: 1586915724319
    name: UserPasswordReset
    parameters: []
    parentId: fld_a2d0e0de6c984471bfb0d0cbef41a924
    settingDisableRenderRequestBody: false
    settingEncodeUrl: true
    settingFollowRedirects: global
    settingRebuildPath: true
    settingSendCookies: true
    settingStoreCookies: true
    url: "{{ graphqlUri  }}"
    _type: request
  - _id: req_a45808c27709424eb7f276ff0e687791
    authentication: {}
    body:
      mimeType: application/graphql
      text: '{"query":"mutation UserPasswordResetRequest($input:
        UserPasswordResetRequestInput!) {\n  userPasswordResetRequest(input:
        $input)\n}\n","variables":{"input":{"id":"ck906nyj9000005lte5zt0pju","notificationMethod":"EMAIL"}},"operationName":"UserPasswordResetRequest"}'
    created: 1586617620607
    description: ""
    headers:
      - id: pair_da0e8e267c1940c0912468bcba4fcc12
        name: Content-Type
        value: application/json
    isPrivate: false
    metaSortKey: -1578263622724.4375
    method: POST
    modified: 1586915628047
    name: UserPasswordResetRequest
    parameters: []
    parentId: fld_a2d0e0de6c984471bfb0d0cbef41a924
    settingDisableRenderRequestBody: false
    settingEncodeUrl: true
    settingFollowRedirects: global
    settingRebuildPath: true
    settingSendCookies: true
    settingStoreCookies: true
    url: "{{ graphqlUri  }}"
    _type: request
  - _id: req_bad1e991f27e4489852519bdf4af1576
    authentication:
      prefix: "{{ accessTokenPrefix  }}"
      token: "{{accessToken}}"
      type: bearer
    body:
      mimeType: application/graphql
      text: '{"query":"mutation UserRevokeRefreshTokens($id: ID!)
        {\n  userRevokeRefreshTokens(id:
        $id)\n}\n","variables":{"id":"ck8u9e30w0000lgfk95ayhq60"},"operationName":"UserRevokeRefreshTokens"}'
    created: 1577823874931
    description: ""
    headers:
      - id: pair_da0e8e267c1940c0912468bcba4fcc12
        name: Content-Type
        value: application/json
    isPrivate: false
    metaSortKey: -1578263622713.5
    method: POST
    modified: 1586915764073
    name: UserRevokeRefreshTokens
    parameters: []
    parentId: fld_a2d0e0de6c984471bfb0d0cbef41a924
    settingDisableRenderRequestBody: false
    settingEncodeUrl: true
    settingFollowRedirects: global
    settingRebuildPath: true
    settingSendCookies: true
    settingStoreCookies: true
    url: "{{ graphqlUri  }}"
    _type: request
  - _id: req_0e4e2585af734dabaf3b4b05d9f2471e
    authentication:
      prefix: "{{ accessTokenPrefix  }}"
      token: "{{accessToken}}"
      type: bearer
    body:
      mimeType: application/graphql
      text: '{"query":"mutation UserSelfSecurityUpdate($input:
        UserSelfSecurityUpdateInput!) {\n  userSelfSecurityUpdate(input:
        $input)\n}\n","variables":{"input":{"passwordCurrent":"Password!23","passwordNew":"Password!23"}},"operationName":"UserSelfSecurityUpdate"}'
    created: 1586208533522
    description: ""
    headers:
      - id: pair_da0e8e267c1940c0912468bcba4fcc12
        name: Content-Type
        value: application/json
    isPrivate: false
    metaSortKey: -1578263622710.375
    method: POST
    modified: 1586915763160
    name: UserSelfSecurityUpdate
    parameters: []
    parentId: fld_a2d0e0de6c984471bfb0d0cbef41a924
    settingDisableRenderRequestBody: false
    settingEncodeUrl: true
    settingFollowRedirects: global
    settingRebuildPath: true
    settingSendCookies: true
    settingStoreCookies: true
    url: "{{ graphqlUri  }}"
    _type: request
  - _id: req_af25446c00a04c87a0e652ffd78dc470
    authentication:
      prefix: "{{ accessTokenPrefix  }}"
      token: "{{accessToken}}"
      type: bearer
    body:
      mimeType: application/graphql
      text: '{"query":"mutation UserSelfUpdate($input: UserSelfUpdateInput!)
        {\n  userSelfUpdate(input: $input)
        {\n    ...userSnapshotFragment\n  }\n}\n\n\nfragment
        userSnapshotFragment on UserSnapshot
        {\n  id\n  email\n  familyName\n  givenName\n  role\n  username\n}","variables":{"input":{"email":"n8@n8io.com","givenName":"Nathan"}},"operationName":"UserSelfUpdate"}'
    created: 1579266441078
    description: ""
    headers:
      - id: pair_da0e8e267c1940c0912468bcba4fcc12
        name: Content-Type
        value: application/json
    isPrivate: false
    metaSortKey: -1578263622707.25
    method: POST
    modified: 1586688925857
    name: UserSelfUpdate
    parameters: []
    parentId: fld_a2d0e0de6c984471bfb0d0cbef41a924
    settingDisableRenderRequestBody: false
    settingEncodeUrl: true
    settingFollowRedirects: global
    settingRebuildPath: true
    settingSendCookies: true
    settingStoreCookies: true
    url: "{{ graphqlUri  }}"
    _type: request
  - _id: req_417eb9126d6e4f48b4bf90a81023e82c
    authentication:
      prefix: "{{ accessTokenPrefix  }}"
      token: "{{accessToken}}"
      type: bearer
    body:
      mimeType: application/graphql
      text: '{"query":"mutation UserDelete($id: ID!) {\n  userDelete(id:
        $id)\n}\n","variables":{"id":"ck8kfnf9c000019fk4c6sd67k"},"operationName":"UserDelete"}'
    created: 1578180146440
    description: ""
    headers:
      - id: pair_da0e8e267c1940c0912468bcba4fcc12
        name: Content-Type
        value: application/json
    isPrivate: false
    metaSortKey: -1578263622701
    method: POST
    modified: 1586915761667
    name: UserDelete
    parameters: []
    parentId: fld_a2d0e0de6c984471bfb0d0cbef41a924
    settingDisableRenderRequestBody: false
    settingEncodeUrl: true
    settingFollowRedirects: global
    settingRebuildPath: true
    settingSendCookies: true
    settingStoreCookies: true
    url: "{{ graphqlUri  }}"
    _type: request
  - _id: req_b14b77bd223c4a4389bfc01c92af31e3
    authentication:
      prefix: "{{ accessTokenPrefix  }}"
      token: "{{ accessToken }}"
      type: bearer
    body:
      mimeType: application/graphql
      text: '{"query":"query SystemTime
        {\n  systemTime\n}","operationName":"SystemTime"}'
    created: 1586689198209
    description: ""
    headers:
      - id: pair_da0e8e267c1940c0912468bcba4fcc12
        name: Content-Type
        value: application/json
    isPrivate: false
    metaSortKey: -1577800601569.75
    method: POST
    modified: 1586915767254
    name: SystemTime
    parameters: []
    parentId: fld_16d435bc119b4cc2af547a3f4de21aa9
    settingDisableRenderRequestBody: false
    settingEncodeUrl: true
    settingFollowRedirects: global
    settingRebuildPath: true
    settingSendCookies: true
    settingStoreCookies: true
    url: "{{ graphqlUri  }}"
    _type: request
  - _id: fld_16d435bc119b4cc2af547a3f4de21aa9
    created: 1577823926119
    description: ""
    environment: {}
    environmentPropertyOrder: null
    metaSortKey: -1577823926119
    modified: 1577823926119
    name: Queries
    parentId: fld_9671057628d34a3bb9e7551fc59663c7
    _type: request_group
  - _id: req_cb754ee6e48a4a44a88808f20e01933b
    authentication: {}
    body:
      mimeType: application/graphql
      text: '{"query":"query UserPasswordResetTokenValidate($input:
        UserPasswordResetTokenValidateInput!)
        {\n  userPasswordResetTokenValidate(input:
        $input)\n}\n","variables":{"input":{"token":"k90olgza0004pyfk7c0kg3bp"}},"operationName":"UserPasswordResetTokenValidate"}'
    created: 1586777712125
    description: ""
    headers:
      - id: pair_da0e8e267c1940c0912468bcba4fcc12
        name: Content-Type
        value: application/json
    isPrivate: false
    metaSortKey: -1577800601544.75
    method: POST
    modified: 1586915695454
    name: UserPasswordResetTokenValidate
    parameters: []
    parentId: fld_16d435bc119b4cc2af547a3f4de21aa9
    settingDisableRenderRequestBody: false
    settingEncodeUrl: true
    settingFollowRedirects: global
    settingRebuildPath: true
    settingSendCookies: true
    settingStoreCookies: true
    url: "{{ graphqlUri  }}"
    _type: request
  - _id: req_4a8fa47b9ee243ae9049bc4f574a51cd
    authentication: {}
    body:
      mimeType: application/graphql
      text: '{"query":"query UserRecoveryFind($account:
        String!){\n  userRecoveryFind(account: $account)
        {\n    ...userRecoveryFragment\n  }\n}\n\nfragment userRecoveryFragment
        on UserRecovery
        {\n  id\n  email\n}","variables":{"account":"n8@N8io.com"},"operationName":"UserRecoveryFind"}'
    created: 1586530625217
    description: ""
    headers:
      - id: pair_da0e8e267c1940c0912468bcba4fcc12
        name: Content-Type
        value: application/json
    isPrivate: false
    metaSortKey: -1577800601519.75
    method: POST
    modified: 1586915586352
    name: UserRecoveryFind
    parameters: []
    parentId: fld_16d435bc119b4cc2af547a3f4de21aa9
    settingDisableRenderRequestBody: false
    settingEncodeUrl: true
    settingFollowRedirects: global
    settingRebuildPath: true
    settingSendCookies: true
    settingStoreCookies: true
    url: "{{ graphqlUri  }}"
    _type: request
  - _id: req_357edaad69cf4b61b0799bd9d18310d7
    authentication:
      prefix: "{{ accessTokenPrefix  }}"
      token: "{{ accessToken }}"
      type: bearer
    body:
      mimeType: application/graphql
      text: '{"query":"query Users($input: PaginationInput!) {\n  users(input:
        $input) {\n    edges {\n      cursor\n      node
        {\n        ...userSnapshotFragment\n      }\n    }\n    pageInfo
        {\n      ...pageInfoFragment\n    }\n  }\n}\n\nfragment pageInfoFragment
        on PageInfo {\n  endCursor\n  hasNextPage\n  total\n}\n\nfragment
        userSnapshotFragment on UserSnapshot
        {\n  id\n  email\n  familyName\n  givenName\n  role\n  username\n}","variables":{"input":{"after":null,"first":null}},"operationName":"Users"}'
    created: 1585738532714
    description: ""
    headers:
      - id: pair_da0e8e267c1940c0912468bcba4fcc12
        name: Content-Type
        value: application/json
    isPrivate: false
    metaSortKey: -1577800601469.75
    method: POST
    modified: 1586915834452
    name: Users
    parameters: []
    parentId: fld_16d435bc119b4cc2af547a3f4de21aa9
    settingDisableRenderRequestBody: false
    settingEncodeUrl: true
    settingFollowRedirects: global
    settingRebuildPath: true
    settingSendCookies: true
    settingStoreCookies: true
    url: "{{ graphqlUri  }}"
    _type: request
  - _id: req_a9caaa314320467f95ab9791d928d190
    authentication:
      prefix: "{{ accessTokenPrefix  }}"
      token: "{{ accessToken }}"
      type: bearer
    body:
      mimeType: application/graphql
      text: '{"query":"query UserSelf {\n  userSelf
        {\n    ...userSnapshotFragment\n  }\n}\n\nfragment userSnapshotFragment
        on UserSnapshot
        {\n  id\n  email\n  familyName\n  givenName\n  role\n  username\n}","operationName":"UserSelf"}'
    created: 1577901244900
    description: ""
    headers:
      - id: pair_da0e8e267c1940c0912468bcba4fcc12
        name: Content-Type
        value: application/json
    isPrivate: false
    metaSortKey: -1577800601463.5
    method: POST
    modified: 1586976235030
    name: UserSelf
    parameters: []
    parentId: fld_16d435bc119b4cc2af547a3f4de21aa9
    settingDisableRenderRequestBody: false
    settingEncodeUrl: true
    settingFollowRedirects: global
    settingRebuildPath: true
    settingSendCookies: true
    settingStoreCookies: true
    url: "{{ graphqlUri  }}"
    _type: request
  - _id: req_a3da66349248459a870b5b6d10fc6d57
    authentication: {}
    body: {}
    created: 1577800722506
    description: ""
    headers: []
    isPrivate: false
    metaSortKey: -1577800382876
    method: GET
    modified: 1577800733685
    name: Heartbeat
    parameters: []
    parentId: fld_09a181bb01a94635bd4fabedb0895ffe
    settingDisableRenderRequestBody: false
    settingEncodeUrl: true
    settingFollowRedirects: global
    settingRebuildPath: true
    settingSendCookies: true
    settingStoreCookies: true
    url: "{{ restUri  }}"
    _type: request
  - _id: fld_09a181bb01a94635bd4fabedb0895ffe
    created: 1577800574602
    description: ""
    environment: {}
    environmentPropertyOrder: null
    metaSortKey: -1577800580826
    modified: 1578619975512
    name: Rest
    parentId: wrk_b673aad6c5df416ead4f262eb230cf9c
    _type: request_group
  - _id: req_2d29ad0fa79b4545b86258fd4216bdad
    authentication: {}
    body: {}
    created: 1577800382825
    description: ""
    headers: []
    isPrivate: false
    metaSortKey: -1577800382826
    method: POST
    modified: 1578146104536
    name: Refresh Token
    parameters: []
    parentId: fld_09a181bb01a94635bd4fabedb0895ffe
    settingDisableRenderRequestBody: false
    settingEncodeUrl: true
    settingFollowRedirects: global
    settingRebuildPath: true
    settingSendCookies: true
    settingStoreCookies: true
    url: "{{refreshTokenUri}}"
    _type: request
  - _id: env_3777c4c8f5c471b0057e66df7c6ad8e43c72a852
    color: null
    created: 1577800360941
    data:
      accessToken: "{% response 'body', 'req_2d29ad0fa79b4545b86258fd4216bdad',
        'b64::JC50b2tlbg==::46b', 'always' %}"
      accessTokenPrefix: bearer
      endpoint: "{{ protocol  }}://{{ host  }}:{{port}}"
      graphqlUri: "{{endpoint}}/graphql"
      host: localhost
      port: 4000
      protocol: http
      refreshToken: "{% request 'cookie', 'jid', 0 %}"
      refreshTokenUri: "{{ endpoint  }}/refresh_token"
      restUri: "{{endpoint}}"
    dataPropertyOrder:
      "&":
        - accessToken
        - accessTokenPrefix
        - endpoint
        - graphqlUri
        - host
        - port
        - protocol
        - refreshToken
        - refreshTokenUri
        - restUri
    isPrivate: false
    metaSortKey: 1577800360941
    modified: 1585947975423
    name: Base Environment
    parentId: wrk_b673aad6c5df416ead4f262eb230cf9c
    _type: environment
  - _id: jar_3777c4c8f5c471b0057e66df7c6ad8e43c72a852
    cookies:
      - creation: 2020-01-14T00:36:22.738Z
        domain: localhost
        expires: 2020-04-24T17:58:57.000Z
        hostOnly: true
        httpOnly: true
        id: "8869459014581189"
        key: jid
        lastAccessed: 2020-04-17T17:58:57.445Z
        maxAge: 604800
        path: /refresh_token
        value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im5jbGFya0BiZWNrbWFuLmNvbSIsImlkIjoiY2s5MDZueWo5MDAwMDA1bHRlNXp0MHBqdSIsInJvbGUiOiJVU0VSIiwidG9rZW5WZXJzaW9uIjowLCJ1c2VybmFtZSI6Im5jbGFyayIsImlhdCI6MTU4NzE0NjMzNywiZXhwIjoxNTg3NzUxMTM3fQ.56qhPDp_sdRTdvfEZiLgBlzreI9MJ1Uby6CjjNkkCoQ
    created: 1577800360958
    modified: 1587146337445
    name: Default Jar
    parentId: wrk_b673aad6c5df416ead4f262eb230cf9c
    _type: cookie_jar
