_type: export
__export_format: 4
__export_date: 2020-04-07T17:25:38.628Z
__export_source: insomnia.desktop.app:v7.1.1
resources:
  - _id: req_45c96e3cce6845569aaeb3db515b8cc3
    authentication: {}
    body:
      mimeType: application/graphql
      text: '{"query":"mutation UserLogin($input: UserLoginInput!)
        {\n  userLogin(input:
        $input)\n}\n","variables":{"input":{"username":"n8io","password":"Password!23"}}}'
    created: 1577800601451
    description: ""
    headers:
      - id: pair_da0e8e267c1940c0912468bcba4fcc12
        name: Content-Type
        value: application/json
    isPrivate: false
    metaSortKey: -1578263622751
    method: POST
    modified: 1586208597191
    name: UserLogin
    parameters: []
    parentId: fld_a2d0e0de6c984471bfb0d0cbef41a924
    settingDisableRenderRequestBody: false
    settingEncodeUrl: true
    settingFollowRedirects: global
    settingRebuildPath: true
    settingSendCookies: true
    settingStoreCookies: true
    url: "{{ graphqlUri  }}"
    _type: request
  - _id: fld_a2d0e0de6c984471bfb0d0cbef41a924
    created: 1577823938455
    description: ""
    environment: {}
    environmentPropertyOrder: null
    metaSortKey: -1577823938455
    modified: 1577823938455
    name: Mutations
    parentId: fld_9671057628d34a3bb9e7551fc59663c7
    _type: request_group
  - _id: fld_9671057628d34a3bb9e7551fc59663c7
    created: 1577801584588
    description: ""
    environment: {}
    environmentPropertyOrder: null
    metaSortKey: -1577801584588
    modified: 1577801584588
    name: User
    parentId: fld_4cbdf86a24044058bb7c82a348286bb7
    _type: request_group
  - _id: fld_4cbdf86a24044058bb7c82a348286bb7
    created: 1577800580776
    description: ""
    environment: {}
    environmentPropertyOrder: null
    metaSortKey: -1577800580876
    modified: 1578620103805
    name: GraphQL
    parentId: wrk_b673aad6c5df416ead4f262eb230cf9c
    _type: request_group
  - _id: wrk_b673aad6c5df416ead4f262eb230cf9c
    created: 1577800360578
    description: ""
    modified: 1577800755606
    name: "@boilerplate-monorepo"
    parentId: null
    _type: workspace
  - _id: req_cea84b50cb754a67bdc1c4cc0d72a250
    authentication:
      prefix: "{{ accessTokenPrefix  }}"
      token: "{{ accessToken }}"
      type: bearer
    body:
      mimeType: application/graphql
      text: '{"query":"mutation UserLogout
        {\n  userLogout\n}\n","operationName":"UserLogout"}'
    created: 1578962079443
    description: ""
    headers:
      - id: pair_da0e8e267c1940c0912468bcba4fcc12
        name: Content-Type
        value: application/json
    isPrivate: false
    metaSortKey: -1578263622738.5
    method: POST
    modified: 1585947922404
    name: UserLogout
    parameters: []
    parentId: fld_a2d0e0de6c984471bfb0d0cbef41a924
    settingDisableRenderRequestBody: false
    settingEncodeUrl: true
    settingFollowRedirects: global
    settingRebuildPath: true
    settingSendCookies: true
    settingStoreCookies: true
    url: "{{ graphqlUri  }}"
    _type: request
  - _id: req_24cc628cbee24f02adca311ed17f5c03
    authentication: {}
    body:
      mimeType: application/graphql
      text: '{"query":"mutation UserRegister($input:
        UserRegisterInput!){\n  userRegister(input:
        $input)\n}\n","variables":{"input":{"givenName":"Jason","familyName":"Pero","email":"test@test2.com","password":"Password!23","username":"jpero"}},"operationName":"UserRegister"}'
    created: 1577801562443
    description: ""
    headers:
      - id: pair_da0e8e267c1940c0912468bcba4fcc12
        name: Content-Type
        value: application/json
    isPrivate: false
    metaSortKey: -1578263622726
    method: POST
    modified: 1586117588694
    name: UserRegister
    parameters: []
    parentId: fld_a2d0e0de6c984471bfb0d0cbef41a924
    settingDisableRenderRequestBody: false
    settingEncodeUrl: true
    settingFollowRedirects: global
    settingRebuildPath: true
    settingSendCookies: true
    settingStoreCookies: true
    url: "{{ graphqlUri  }}"
    _type: request
  - _id: req_bad1e991f27e4489852519bdf4af1576
    authentication:
      prefix: "{{ accessTokenPrefix  }}"
      token: "{{accessToken}}"
      type: bearer
    body:
      mimeType: application/graphql
      text: '{"query":"mutation UserRevokeRefreshTokens($id: String!)
        {\n  userRevokeRefreshTokens(id:
        $id)\n}\n","variables":{"id":"ck4zo095l000069z8ht9rfh4z"}}'
    created: 1577823874931
    description: ""
    headers:
      - id: pair_da0e8e267c1940c0912468bcba4fcc12
        name: Content-Type
        value: application/json
    isPrivate: false
    metaSortKey: -1578263622713.5
    method: POST
    modified: 1584431658592
    name: UserRevokeRefreshTokens
    parameters: []
    parentId: fld_a2d0e0de6c984471bfb0d0cbef41a924
    settingDisableRenderRequestBody: false
    settingEncodeUrl: true
    settingFollowRedirects: global
    settingRebuildPath: true
    settingSendCookies: true
    settingStoreCookies: true
    url: "{{ graphqlUri  }}"
    _type: request
  - _id: req_0e4e2585af734dabaf3b4b05d9f2471e
    authentication:
      prefix: "{{ accessTokenPrefix  }}"
      token: "{{accessToken}}"
      type: bearer
    body:
      mimeType: application/graphql
      text: '{"query":"mutation UserSelfSecurityUpdate($input:
        UserSelfSecurityUpdateInput!) {\n  userSelfSecurityUpdate(input:
        $input)\n}\n","variables":{"input":{"passwordCurrent":"Nathan","passwordNew":"Password!23"}},"operationName":"UserSelfSecurityUpdate"}'
    created: 1586208533522
    description: ""
    headers:
      - id: pair_da0e8e267c1940c0912468bcba4fcc12
        name: Content-Type
        value: application/json
    isPrivate: false
    metaSortKey: -1578263622710.375
    method: POST
    modified: 1586209438407
    name: UserSelfSecurityUpdate
    parameters: []
    parentId: fld_a2d0e0de6c984471bfb0d0cbef41a924
    settingDisableRenderRequestBody: false
    settingEncodeUrl: true
    settingFollowRedirects: global
    settingRebuildPath: true
    settingSendCookies: true
    settingStoreCookies: true
    url: "{{ graphqlUri  }}"
    _type: request
  - _id: req_af25446c00a04c87a0e652ffd78dc470
    authentication:
      prefix: "{{ accessTokenPrefix  }}"
      token: "{{accessToken}}"
      type: bearer
    body:
      mimeType: application/graphql
      text: '{"query":"mutation UserSelfUpdate($input: UserSelfUpdateInput!)
        {\n  userSelfUpdate(input: $input)
        {\n    ...userSnapshotFragment\n  }\n}\n\n\nfragment
        userSnapshotFragment on UserSnapshot
        {\n  id\n  email\n  familyName\n  givenName\n  role\n  username\n}","variables":{"input":{"email":"n8@n8io.com","givenName":"Nathan"}},"operationName":"UserSelfUpdate"}'
    created: 1579266441078
    description: ""
    headers:
      - id: pair_da0e8e267c1940c0912468bcba4fcc12
        name: Content-Type
        value: application/json
    isPrivate: false
    metaSortKey: -1578263622707.25
    method: POST
    modified: 1586208525634
    name: UserSelfUpdate
    parameters: []
    parentId: fld_a2d0e0de6c984471bfb0d0cbef41a924
    settingDisableRenderRequestBody: false
    settingEncodeUrl: true
    settingFollowRedirects: global
    settingRebuildPath: true
    settingSendCookies: true
    settingStoreCookies: true
    url: "{{ graphqlUri  }}"
    _type: request
  - _id: req_417eb9126d6e4f48b4bf90a81023e82c
    authentication:
      prefix: "{{ accessTokenPrefix  }}"
      token: "{{accessToken}}"
      type: bearer
    body:
      mimeType: application/graphql
      text: '{"query":"mutation UserDelete($id: ID!) {\n  userDelete(id:
        $id)\n}\n","variables":{"id":"ck8kfnf9c000019fk4c6sd67k"},"operationName":"UserDelete"}'
    created: 1578180146440
    description: ""
    headers:
      - id: pair_da0e8e267c1940c0912468bcba4fcc12
        name: Content-Type
        value: application/json
    isPrivate: false
    metaSortKey: -1578263622701
    method: POST
    modified: 1586097479069
    name: UserDelete
    parameters: []
    parentId: fld_a2d0e0de6c984471bfb0d0cbef41a924
    settingDisableRenderRequestBody: false
    settingEncodeUrl: true
    settingFollowRedirects: global
    settingRebuildPath: true
    settingSendCookies: true
    settingStoreCookies: true
    url: "{{ graphqlUri  }}"
    _type: request
  - _id: req_357edaad69cf4b61b0799bd9d18310d7
    authentication:
      prefix: "{{ accessTokenPrefix  }}"
      token: "{{ accessToken }}"
      type: bearer
    body:
      mimeType: application/graphql
      text: '{"query":"query Users($input: PaginationInput!) {\n  users(input:
        $input) {\n    edges {\n      cursor\n      node
        {\n        ...userSnapshotFragment\n      }\n    }\n    pageInfo
        {\n      ...pageInfoFragment\n    }\n  }\n}\n\nfragment pageInfoFragment
        on PageInfo {\n  endCursor\n  hasNextPage\n  total\n}\n\nfragment
        userSnapshotFragment on UserSnapshot
        {\n  id\n  email\n  familyName\n  givenName\n  role\n  username\n}","variables":{"input":{"after":null,"first":null}},"operationName":"Users"}'
    created: 1585738532714
    description: ""
    headers:
      - id: pair_da0e8e267c1940c0912468bcba4fcc12
        name: Content-Type
        value: application/json
    isPrivate: false
    metaSortKey: -1577800601469.75
    method: POST
    modified: 1586117468958
    name: Users
    parameters: []
    parentId: fld_16d435bc119b4cc2af547a3f4de21aa9
    settingDisableRenderRequestBody: false
    settingEncodeUrl: true
    settingFollowRedirects: global
    settingRebuildPath: true
    settingSendCookies: true
    settingStoreCookies: true
    url: "{{ graphqlUri  }}"
    _type: request
  - _id: fld_16d435bc119b4cc2af547a3f4de21aa9
    created: 1577823926119
    description: ""
    environment: {}
    environmentPropertyOrder: null
    metaSortKey: -1577823926119
    modified: 1577823926119
    name: Queries
    parentId: fld_9671057628d34a3bb9e7551fc59663c7
    _type: request_group
  - _id: req_a9caaa314320467f95ab9791d928d190
    authentication:
      prefix: "{{ accessTokenPrefix  }}"
      token: "{{ accessToken }}"
      type: bearer
    body:
      mimeType: application/graphql
      text: '{"query":"query UserSelf {\n  userSelf
        {\n    ...userSnapshotFragment\n  }\n}\n\nfragment userSnapshotFragment
        on UserSnapshot
        {\n  id\n  email\n  familyName\n  givenName\n  role\n  username\n}","operationName":"UserSelf"}'
    created: 1577901244900
    description: ""
    headers:
      - id: pair_da0e8e267c1940c0912468bcba4fcc12
        name: Content-Type
        value: application/json
    isPrivate: false
    metaSortKey: -1577800601463.5
    method: POST
    modified: 1586119148922
    name: UserSelf
    parameters: []
    parentId: fld_16d435bc119b4cc2af547a3f4de21aa9
    settingDisableRenderRequestBody: false
    settingEncodeUrl: true
    settingFollowRedirects: global
    settingRebuildPath: true
    settingSendCookies: true
    settingStoreCookies: true
    url: "{{ graphqlUri  }}"
    _type: request
  - _id: req_a3da66349248459a870b5b6d10fc6d57
    authentication: {}
    body: {}
    created: 1577800722506
    description: ""
    headers: []
    isPrivate: false
    metaSortKey: -1577800382876
    method: GET
    modified: 1577800733685
    name: Heartbeat
    parameters: []
    parentId: fld_09a181bb01a94635bd4fabedb0895ffe
    settingDisableRenderRequestBody: false
    settingEncodeUrl: true
    settingFollowRedirects: global
    settingRebuildPath: true
    settingSendCookies: true
    settingStoreCookies: true
    url: "{{ restUri  }}"
    _type: request
  - _id: fld_09a181bb01a94635bd4fabedb0895ffe
    created: 1577800574602
    description: ""
    environment: {}
    environmentPropertyOrder: null
    metaSortKey: -1577800580826
    modified: 1578619975512
    name: Rest
    parentId: wrk_b673aad6c5df416ead4f262eb230cf9c
    _type: request_group
  - _id: req_2d29ad0fa79b4545b86258fd4216bdad
    authentication: {}
    body: {}
    created: 1577800382825
    description: ""
    headers: []
    isPrivate: false
    metaSortKey: -1577800382826
    method: POST
    modified: 1578146104536
    name: Refresh Token
    parameters: []
    parentId: fld_09a181bb01a94635bd4fabedb0895ffe
    settingDisableRenderRequestBody: false
    settingEncodeUrl: true
    settingFollowRedirects: global
    settingRebuildPath: true
    settingSendCookies: true
    settingStoreCookies: true
    url: "{{refreshTokenUri}}"
    _type: request
  - _id: env_3777c4c8f5c471b0057e66df7c6ad8e43c72a852
    color: null
    created: 1577800360941
    data:
      accessToken: "{% response 'body', 'req_2d29ad0fa79b4545b86258fd4216bdad',
        'b64::JC50b2tlbg==::46b', 'always' %}"
      accessTokenPrefix: bearer
      endpoint: "{{ protocol  }}://{{ host  }}:{{port}}"
      graphqlUri: "{{endpoint}}/graphql"
      host: localhost
      port: 4000
      protocol: http
      refreshToken: "{% request 'cookie', 'jid', 0 %}"
      refreshTokenUri: "{{ endpoint  }}/refresh_token"
      restUri: "{{endpoint}}"
    dataPropertyOrder:
      "&":
        - accessToken
        - accessTokenPrefix
        - endpoint
        - graphqlUri
        - host
        - port
        - protocol
        - refreshToken
        - refreshTokenUri
        - restUri
    isPrivate: false
    metaSortKey: 1577800360941
    modified: 1585947975423
    name: Base Environment
    parentId: wrk_b673aad6c5df416ead4f262eb230cf9c
    _type: environment
  - _id: jar_3777c4c8f5c471b0057e66df7c6ad8e43c72a852
    cookies:
      - creation: 2020-01-14T00:36:22.738Z
        domain: localhost
        expires: 2020-04-13T21:43:59.000Z
        hostOnly: true
        httpOnly: true
        id: "9585112017117978"
        key: jid
        lastAccessed: 2020-04-06T21:43:59.038Z
        maxAge: 604800
        path: /refresh_token
        value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im44QG44aW8uY29tIiwiaWQiOiJjazhmNXRkeXQwMDAwajBmazhyZ2Q3amNjIiwicm9sZSI6IkFETUlOIiwidG9rZW5WZXJzaW9uIjowLCJ1c2VybmFtZSI6Im44aW8iLCJpYXQiOjE1ODYyMDk0MzksImV4cCI6MTU4NjgxNDIzOX0.NUEDctLLQdlW-3jIMS8NyZcPIPTSGSPYHCVANApOIVQ
    created: 1577800360958
    modified: 1586209439038
    name: Default Jar
    parentId: wrk_b673aad6c5df416ead4f262eb230cf9c
    _type: cookie_jar
