_type: export
__export_format: 4
__export_date: 2020-01-03T03:42:39.755Z
__export_source: insomnia.desktop.app:v7.0.6
resources:
  - _id: req_45c96e3cce6845569aaeb3db515b8cc3
    authentication: {}
    body:
      mimeType: application/graphql
      text: '{"query":"mutation Login($input: LoginInput!) {\n  login(input:
        $input)\n}\n","variables":{"input":{"username":"test","password":"test"}},"operationName":"Login"}'
    created: 1577800601451
    description: ""
    headers:
      - id: pair_da0e8e267c1940c0912468bcba4fcc12
        name: Content-Type
        value: application/json
    isPrivate: false
    metaSortKey: -1577800601551
    method: POST
    modified: 1577972284524
    name: Login
    parameters: []
    parentId: fld_a2d0e0de6c984471bfb0d0cbef41a924
    settingDisableRenderRequestBody: false
    settingEncodeUrl: true
    settingFollowRedirects: global
    settingRebuildPath: true
    settingSendCookies: true
    settingStoreCookies: true
    url: "{{ graphqlUri  }}"
    _type: request
  - _id: fld_a2d0e0de6c984471bfb0d0cbef41a924
    created: 1577823938455
    description: ""
    environment: {}
    environmentPropertyOrder: null
    metaSortKey: -1577823938455
    modified: 1577823938455
    name: Mutations
    parentId: fld_9671057628d34a3bb9e7551fc59663c7
    _type: request_group
  - _id: fld_9671057628d34a3bb9e7551fc59663c7
    created: 1577801584588
    description: ""
    environment: {}
    environmentPropertyOrder: null
    metaSortKey: -1577801584588
    modified: 1577801584588
    name: User
    parentId: fld_4cbdf86a24044058bb7c82a348286bb7
    _type: request_group
  - _id: fld_4cbdf86a24044058bb7c82a348286bb7
    created: 1577800580776
    description: ""
    environment: {}
    environmentPropertyOrder: null
    metaSortKey: -1577800580776
    modified: 1577800589884
    name: GraphQL
    parentId: wrk_b673aad6c5df416ead4f262eb230cf9c
    _type: request_group
  - _id: wrk_b673aad6c5df416ead4f262eb230cf9c
    created: 1577800360578
    description: ""
    modified: 1577800755606
    name: "@boilerplate-monorepo"
    parentId: null
    _type: workspace
  - _id: req_24cc628cbee24f02adca311ed17f5c03
    authentication: {}
    body:
      mimeType: application/graphql
      text: '{"query":"mutation Register($input: RegisterInput!){\n  register(input:
        $input)\n}\n","variables":{"input":{"email":"test@test.com","password":"test","username":"test"}},"operationName":"Register"}'
    created: 1577801562443
    description: ""
    headers:
      - id: pair_da0e8e267c1940c0912468bcba4fcc12
        name: Content-Type
        value: application/json
    isPrivate: false
    metaSortKey: -1577800601526
    method: POST
    modified: 1577972263307
    name: Register
    parameters: []
    parentId: fld_a2d0e0de6c984471bfb0d0cbef41a924
    settingDisableRenderRequestBody: false
    settingEncodeUrl: true
    settingFollowRedirects: global
    settingRebuildPath: true
    settingSendCookies: true
    settingStoreCookies: true
    url: "{{ graphqlUri  }}"
    _type: request
  - _id: req_bad1e991f27e4489852519bdf4af1576
    authentication: {}
    body:
      mimeType: application/graphql
      text: '{"query":"mutation RevokeRefreshTokens($id: String!)
        {\n  revokeRefreshTokens(id:
        $id)\n}\n","variables":{"id":"ck4wrxzjk0000ztad83vkb95q"},"operationName":"RevokeRefreshTokens"}'
    created: 1577823874931
    description: ""
    headers:
      - id: pair_da0e8e267c1940c0912468bcba4fcc12
        name: Content-Type
        value: application/json
    isPrivate: false
    metaSortKey: -1577800601501
    method: POST
    modified: 1577972345393
    name: RevokeRefreshTokens
    parameters: []
    parentId: fld_a2d0e0de6c984471bfb0d0cbef41a924
    settingDisableRenderRequestBody: false
    settingEncodeUrl: true
    settingFollowRedirects: global
    settingRebuildPath: true
    settingSendCookies: true
    settingStoreCookies: true
    url: "{{ graphqlUri  }}"
    _type: request
  - _id: req_692a8825c5124411ad5e18b54bbd5ce4
    authentication:
      prefix: bearer
      token: "{{ jwt  }}"
      type: bearer
    body:
      mimeType: application/graphql
      text: '{"query":"query Users($input: UsersInput!) {\n  users(input: $input)
        {\n    edges {\n      cursor\n      node
        {\n        id\n        email\n        username\n      }\n    }\n    pageInfo
        {\n      endCursor\n      hasNextPage\n    }\n  }\n}\n","variables":{"input":{"after":null,"first":3}},"operationName":"Users"}'
    created: 1577801637149
    description: ""
    headers:
      - id: pair_da0e8e267c1940c0912468bcba4fcc12
        name: Content-Type
        value: application/json
    isPrivate: false
    metaSortKey: -1577800601476
    method: POST
    modified: 1578022902191
    name: Users
    parameters: []
    parentId: fld_16d435bc119b4cc2af547a3f4de21aa9
    settingDisableRenderRequestBody: false
    settingEncodeUrl: true
    settingFollowRedirects: global
    settingRebuildPath: true
    settingSendCookies: true
    settingStoreCookies: true
    url: "{{ graphqlUri  }}"
    _type: request
  - _id: fld_16d435bc119b4cc2af547a3f4de21aa9
    created: 1577823926119
    description: ""
    environment: {}
    environmentPropertyOrder: null
    metaSortKey: -1577823926119
    modified: 1577823926119
    name: Queries
    parentId: fld_9671057628d34a3bb9e7551fc59663c7
    _type: request_group
  - _id: req_a9caaa314320467f95ab9791d928d190
    authentication:
      prefix: bearer
      token: "{{ jwt  }}"
      type: bearer
    body:
      mimeType: application/graphql
      text: '{"query":"query Me {\n  me
        {\n    id\n    email\n    username\n  }\n}\n"}'
    created: 1577901244900
    description: ""
    headers:
      - id: pair_da0e8e267c1940c0912468bcba4fcc12
        name: Content-Type
        value: application/json
    isPrivate: false
    metaSortKey: -1577800601463.5
    method: POST
    modified: 1577901248525
    name: Me
    parameters: []
    parentId: fld_16d435bc119b4cc2af547a3f4de21aa9
    settingDisableRenderRequestBody: false
    settingEncodeUrl: true
    settingFollowRedirects: global
    settingRebuildPath: true
    settingSendCookies: true
    settingStoreCookies: true
    url: "{{ graphqlUri  }}"
    _type: request
  - _id: req_a3da66349248459a870b5b6d10fc6d57
    authentication: {}
    body: {}
    created: 1577800722506
    description: ""
    headers: []
    isPrivate: false
    metaSortKey: -1577800382876
    method: GET
    modified: 1577800733685
    name: Heartbeat
    parameters: []
    parentId: fld_09a181bb01a94635bd4fabedb0895ffe
    settingDisableRenderRequestBody: false
    settingEncodeUrl: true
    settingFollowRedirects: global
    settingRebuildPath: true
    settingSendCookies: true
    settingStoreCookies: true
    url: "{{ restUri  }}"
    _type: request
  - _id: fld_09a181bb01a94635bd4fabedb0895ffe
    created: 1577800574602
    description: ""
    environment: {}
    environmentPropertyOrder: null
    metaSortKey: -1577800574603
    modified: 1577800574602
    name: Rest
    parentId: wrk_b673aad6c5df416ead4f262eb230cf9c
    _type: request_group
  - _id: req_2d29ad0fa79b4545b86258fd4216bdad
    authentication: {}
    body: {}
    created: 1577800382825
    description: ""
    headers: []
    isPrivate: false
    metaSortKey: -1577800382826
    method: POST
    modified: 1577800694031
    name: Refresh Token
    parameters: []
    parentId: fld_09a181bb01a94635bd4fabedb0895ffe
    settingDisableRenderRequestBody: false
    settingEncodeUrl: true
    settingFollowRedirects: global
    settingRebuildPath: true
    settingSendCookies: true
    settingStoreCookies: true
    url: "{{ restUri  }}/refresh_token"
    _type: request
  - _id: env_3777c4c8f5c471b0057e66df7c6ad8e43c72a852
    color: null
    created: 1577800360941
    data:
      endpoint: "{{ protocol  }}://{{ host  }}:{{port}}"
      graphqlUri: "{{endpoint}}/graphql"
      host: localhost
      jwt: "{% response 'body', 'req_45c96e3cce6845569aaeb3db515b8cc3',
        'b64::JC5kYXRhLmxvZ2lu::46b', 'no-history' %}"
      port: 4000
      protocol: http
      restUri: "{{endpoint}}"
    dataPropertyOrder:
      "&":
        - host
        - port
        - protocol
        - endpoint
        - restUri
        - graphqlUri
        - jwt
    isPrivate: false
    metaSortKey: 1577800360941
    modified: 1577827205997
    name: Base Environment
    parentId: wrk_b673aad6c5df416ead4f262eb230cf9c
    _type: environment
  - _id: jar_3777c4c8f5c471b0057e66df7c6ad8e43c72a852
    cookies:
      - creation: 2019-12-31T15:10:32.874Z
        domain: localhost
        hostOnly: true
        httpOnly: true
        id: "16208095735864037"
        key: jid
        lastAccessed: 2020-01-03T03:41:54.988Z
        path: /
        value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAdGVzdC5jb20iLCJpZCI6ImNrNHVnNGdvZjAwMDB4eHo4N2I0N2NtN2YiLCJ0b2tlblZlcnNpb24iOjYsInVzZXJuYW1lIjoidGVzdCIsImlhdCI6MTU3ODAyMjkxNCwiZXhwIjoxNTc4NjI3NzE0fQ.vt1ZIl1z11f_k82ojxZ5--H184bKwTsmCX8mOL1V7vk
    created: 1577800360958
    modified: 1578022914988
    name: Default Jar
    parentId: wrk_b673aad6c5df416ead4f262eb230cf9c
    _type: cookie_jar
