name: Run Tests

on:
  push:
    branches:
      - 'bugs/**'
      - 'features/**'
      - 'chores/**'

jobs:
  no-skip:
    runs-on: ubuntu-latest
    if: "! contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - run: echo "${{ github.event.head_commit.message }}"
  lint-test:
    needs: no-skip
    strategy:
      matrix:
        node-version: [12.x]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install dependencies
        run: |
          npx lerna bootstrap

      - name: Run linters
        run: |
          npm run lint

      - name: Run tests
        run: |
          npm run test
