name: Run Tests

on:
  push:
    branches:
      - 'bugs/**'
      - 'features/**'
      - 'chores/**'

jobs:
  lint-test:
    strategy:
      matrix:
        node-version: [12.x]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install dependencies
        run: npx lerna bootstrap
      - name: Run linters
        run: npm run lint
      - name: Run unit tests
        run: npm run test
      - name: Run integration tests
        uses: cypress-io/github-action@v1
        with:
          browser: chrome
          config-file: cypress/cypress.json
          install: false
          start: npm run start:ui
          wait-on: 'http://localhost:3000'
          wait-on-timeout: 120
